#1º
SELECT COUNT(DISTINCT JOB_ID) FROM employees;
#2º 
SELECT SUM(SALARY) as TOTAL_PAGO FROM employees;
#3º
SELECT MIN(SALARY) as MENOR_SALARIO FROM employees;
#4º
SELECT MAX(SALARY) as MAIOR_SALARIO_PROGRAM FROM employees
WHERE job_id = 'IT_PROG';
#5º
SELECT AVG(SALARY) as MEDIA, COUNT(DEPARTMENT_ID) FROM employees
WHERE DEPARTMENT_ID = 90;
#6º
SELECT MAX(SALARY), MIN(SALARY), SUM(SALARY), AVG(SALARY) FROM employees;
#7º USANDO GROUPSS
SELECT JOB_ID , COUNT(*) FROM employees
GROUP BY JOB_ID;
#8º
SELECT MAX(SALARY) - MIN(SALARY) AS DIFERENCA FROM employees;
#9º
SELECT MANAGER_ID ,MIN(SALARY) FROM employees
GROUP BY MANAGER_ID
ORDER BY MIN(salary) DESC;
#10º
SELECT DEPARTMENT_ID, SUM(SALARY) FROM employees
GROUP BY DEPARTMENT_ID;
#11º
SELECT JOB_ID, AVG(SALARY) AS MEDIA_SALARIO FROM employees
WHERE JOB_ID != 'TI_PROG'
GROUP BY JOB_ID;
#12º
SELECT SUM(SALARY) AS TOTAL, MAX(SALARY) AS MAX, MIN(SALARY) AS MIN, AVG(SALARY) AS MEDIA, JOB_ID FROM employees
WHERE DEPARTMENT_ID = 90
GROUP BY JOB_ID;
#13º
SELECT JOB_ID AS JOB_ID ,MAX(SALARY) AS MAXIMO_SALARIO FROM employees
WHERE SALARY >= 4000
GROUP BY(JOB_ID);
#14º
SELECT DEPARTMENT_ID, AVG(SALARY) AS MEDIA_SALARIO , COUNT(DEPARTMENT_ID) AS FUNCIONARIOS FROM employees
GROUP BY (DEPARTMENT_ID)
HAVING COUNT(DEPARTMENT_ID) > 10;

