#1º Adicionando 3 meses na data atual
SELECT CURDATE()  + INTERVAL 3 MONTH;

#2º
SELECT LAST_DAY(  CURDATE()  + INTERVAL 3 MONTH ) AS RESULTADO;

#3º
SELECT DISTINCT HIRE_DATE
FROM EMPLOYEES
WHERE DAYOFWEEK(HIRE_DATE) = 2;

#4º
SELECT MAKEDATE(YEAR(CURDATE()), 1) AS RESULTADO;

#5º
SELECT MAKEDATE(YEAR(CURDATE()), 31) - INTERVAL 31 DAY + INTERVAL 1 YEAR AS RESULTADO;

#6º IDADE do que? Não entendi o exercicio

#7º LETRAS MAISCULA mudam o formato
SELECT DATE_FORMAT(CURDATE(),'%M %e, %Y') as DATA;

#8º
SELECT DATE_FORMAT(CURDATE(),'%W, %M, %Y') as DATA;

#9º
SELECT YEAR(CURDATE()) AS ANO;

#10º
SELECT FROM_DAYS(730677);

#11º




